# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBcmN_3mqc1bXeAm81GLEjd-qOBLln81
"""

import numpy as np
import matplotlib.pyplot as plt

# Sample Dataset
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)
Y = np.array([2, 4, 5, 4, 5, 7, 8, 9, 10, 12], dtype=float)

# Initialize Parameters
m = 0
b = 0
learning_rate = 0.01
iterations = 1000

n = len(X)
losses = []

# Gradient Descent
for i in range(iterations):

    # Prediction
    Y_pred = m * X + b

    # Mean Squared Error
    loss = (1 / n) * np.sum((Y - Y_pred) ** 2)
    losses.append(loss)

    # Compute Gradients
    dm = (-2 / n) * np.sum(X * (Y - Y_pred))
    db = (-2 / n) * np.sum(Y - Y_pred)

    # Update Parameters
    m = m - learning_rate * dm
    b = b - learning_rate * db

# Print Results
print("Final Weight (m):", round(m, 3))
print("Final Bias (b):", round(b, 3))
print("Final Loss:", round(losses[-1], 4))

# Plot Learning Curve (Skip first 10 iterations for better visualization)
plt.figure(figsize=(6,4))
plt.plot(range(10, iterations), losses[10:], color='blue')
plt.title("Learning Curve")
plt.xlabel("Iterations")
plt.ylabel("Loss (MSE)")
plt.grid(True)
plt.show()

# Plot Regression Line
plt.figure(figsize=(6,4))
plt.scatter(X, Y, color='blue', label='Actual Data')
plt.plot(X, m * X + b, color='red', linewidth=2, label='Regression Line')
plt.title("Linear Regression using Gradient Descent")
plt.xlabel("X")
plt.ylabel("Y")
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Actual Parameters
true_mean = 50
true_std = 5

# Generate Synthetic Data
np.random.seed(42)
data = np.random.normal(true_mean, true_std, 1000)

# MLE Estimation
estimated_mean = np.mean(data)
estimated_variance = np.mean((data - estimated_mean) ** 2)

# Actual Variance
true_variance = true_std ** 2

# Display Results
print("Actual Mean:", true_mean)
print("Estimated Mean:", round(estimated_mean, 2))
print("Actual Variance:", true_variance)
print("Estimated Variance:", round(estimated_variance, 2))

# Plot Histogram
plt.figure(figsize=(6,4))
plt.hist(data, bins=30, edgecolor='black')
plt.title("Histogram of Synthetic Data")
plt.xlabel("Data Values")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")
print("\nConfusion Matrix:")
print(cm)

# Plot Confusion Matrix
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# XOR Dataset
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Build Neural Network
model = Sequential()

# Hidden Layer
model.add(Dense(4, input_dim=2, activation='relu'))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

# Compile Model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train Model
model.fit(X, y, epochs=500, verbose=0)

# Predictions
predictions = model.predict(X)

print("Predicted Values:")
print(np.round(predictions))

# Evaluate Model
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Accuracy:", round(accuracy * 100, 2), "%")

import numpy as np

# Input values
inputs = np.array([1.5, 2.0, -1.0])

# Weights
weights = np.array([0.8, -0.5, 0.3])

# Bias
bias = 0.2

# Weighted Sum
z = np.dot(inputs, weights) + bias

# Sigmoid Activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# ReLU Activation
def relu(x):
    return np.maximum(0, x)

# Outputs
sigmoid_output = sigmoid(z)
relu_output = relu(z)

print("Weighted Sum (z):", round(z, 3))
print("Sigmoid Output:", round(sigmoid_output, 3))
print("ReLU Output:", round(relu_output, 3))

from sklearn.datasets import make_classification, make_circles
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

# Linearly Separable Dataset
X1, y1 = make_classification(n_samples=200,
                             n_features=2,
                             n_redundant=0,
                             n_clusters_per_class=1,
                             random_state=42)

model = Perceptron(max_iter=1000, random_state=42)
model.fit(X1, y1)
pred1 = model.predict(X1)

print("Linearly Separable Accuracy:",
      round(accuracy_score(y1, pred1) * 100, 2), "%")

# Non-Linearly Separable Dataset
X2, y2 = make_circles(n_samples=200,
                      noise=0.1,
                      factor=0.5,
                      random_state=42)

model.fit(X2, y2)
pred2 = model.predict(X2)

print("Non-Linearly Separable Accuracy:",
      round(accuracy_score(y2, pred2) * 100, 2), "%")

from sklearn.datasets import make_circles
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Dataset
X, y = make_circles(n_samples=200,
                    noise=0.1,
                    factor=0.5,
                    random_state=42)

# Perceptron
perceptron = Perceptron(max_iter=1000, random_state=42)
perceptron.fit(X, y)
pred1 = perceptron.predict(X)

# MLP
mlp = MLPClassifier(hidden_layer_sizes=(10,),
                    max_iter=1000,
                    random_state=42)

mlp.fit(X, y)
pred2 = mlp.predict(X)

print("Perceptron Accuracy:",
      round(accuracy_score(y, pred1) * 100, 2), "%")

print("MLP Accuracy:",
      round(accuracy_score(y, pred2) * 100, 2), "%")

import numpy as np

# Inputs
x = np.array([1.0, 2.0])

# Weights
w = np.array([0.5, -0.4])

# Bias
b = 0.2

# Sigmoid Function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Forward Propagation
z = np.dot(x, w) + b
output = sigmoid(z)

print("Weighted Sum (z):", round(z, 3))
print("Network Output:", round(output, 3))

import numpy as np

# Input and Target
x = np.array([1.0, 2.0])
target = 1

# Initial Weights and Bias
w = np.array([0.5, -0.4])
b = 0.2

learning_rate = 0.1

# Sigmoid Function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Derivative of Sigmoid
def sigmoid_derivative(y):
    return y * (1 - y)

# Forward Propagation
z = np.dot(x, w) + b
output = sigmoid(z)

# Error
error = target - output

# Gradient
delta = error * sigmoid_derivative(output)

# Update Weights and Bias
w = w + learning_rate * delta * x
b = b + learning_rate * delta

print("Updated Weights:", np.round(w, 3))
print("Updated Bias:", round(b, 3))

import numpy as np
import matplotlib.pyplot as plt

# Dataset
X = np.array([1,2,3,4,5], dtype=float)
Y = np.array([2,4,6,8,10], dtype=float)

learning_rates = [0.001, 0.01, 0.1]

plt.figure(figsize=(6,4))

for lr in learning_rates:
    w = 0
    b = 0
    losses = []

    for i in range(100):
        y_pred = w * X + b
        loss = np.mean((Y - y_pred) ** 2)
        losses.append(loss)

        dw = (-2/len(X)) * np.sum(X * (Y - y_pred))
        db = (-2/len(X)) * np.sum(Y - y_pred)

        w -= lr * dw
        b -= lr * db

    plt.plot(losses, label=f"LR={lr}")

plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.title("Gradient Descent Learning Rates")
plt.legend()
plt.show()

from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.metrics import mean_squared_error

# Dataset
X, y = make_regression(n_samples=100,
                       n_features=1,
                       noise=10,
                       random_state=42)

# Batch Gradient Descent
batch_model = LinearRegression()
batch_model.fit(X, y)
batch_pred = batch_model.predict(X)

# Stochastic Gradient Descent
sgd_model = SGDRegressor(max_iter=1000,
                         learning_rate='constant',
                         eta0=0.01,
                         random_state=42)

sgd_model.fit(X, y)
sgd_pred = sgd_model.predict(X)

print("Batch GD MSE:",
      round(mean_squared_error(y, batch_pred), 2))

print("SGD MSE:",
      round(mean_squared_error(y, sgd_pred), 2))

import numpy as np
import matplotlib.pyplot as plt

# Create Dataset
X = np.arange(1, 21, dtype=float)
X = X / np.max(X)          # Normalize inputs
Y = 2 * X + 1              # y = 2x + 1

learning_rate = 0.001
epochs = 100
batch_sizes = [1, 5, 10]

plt.figure(figsize=(8,5))

for batch_size in batch_sizes:

    # Initialize parameters
    w = 0.0
    b = 0.0
    losses = []

    for epoch in range(epochs):

        # Shuffle dataset
        indices = np.random.permutation(len(X))
        X_shuffled = X[indices]
        Y_shuffled = Y[indices]

        # Mini-Batch Training
        for i in range(0, len(X), batch_size):

            X_batch = X_shuffled[i:i + batch_size]
            Y_batch = Y_shuffled[i:i + batch_size]

            # Prediction
            Y_pred = w * X_batch + b

            # Gradients
            dw = (-2 / len(X_batch)) * np.sum(X_batch * (Y_batch - Y_pred))
            db = (-2 / len(X_batch)) * np.sum(Y_batch - Y_pred)

            # Update parameters
            w -= learning_rate * dw
            b -= learning_rate * db

        # Calculate loss after each epoch
        Y_pred_all = w * X + b
        loss = np.mean((Y - Y_pred_all) ** 2)
        losses.append(loss)

    plt.plot(losses, linewidth=2, label=f"Batch Size = {batch_size}")

plt.title("Mini-Batch Gradient Descent")
plt.xlabel("Epochs")
plt.ylabel("Mean Squared Error (Loss)")
plt.legend()
plt.grid(True)
plt.show()

# Print final parameters
print("Final Weight:", round(w, 4))
print("Final Bias:", round(b, 4))
print("Final Loss:", round(losses[-1], 6))

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from scipy.spatial.distance import pdist

dimensions = [2, 5, 10, 20, 50]
avg_distances = []
accuracies = []

for dim in dimensions:

    X, y = make_classification(
        n_samples=500,
        n_features=dim,
        n_informative=max(2, dim//2),
        n_redundant=0,
        random_state=42
    )

    # Average distance between points
    avg_distance = np.mean(pdist(X))
    avg_distances.append(avg_distance)

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42
    )

    # KNN Model
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)

    print(f"Dimensions = {dim}, Average Distance = {avg_distance:.2f}, Accuracy = {accuracy:.2f}")

# Plot Results
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.plot(dimensions, avg_distances, marker='o')
plt.title("Dimension vs Average Distance")
plt.xlabel("Dimensions")
plt.ylabel("Average Distance")
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(dimensions, accuracies, marker='o', color='red')
plt.title("Dimension vs Accuracy")
plt.xlabel("Dimensions")
plt.ylabel("Accuracy")
plt.grid(True)

plt.tight_layout()
plt.show()